# Welcome to Serverless!

service: todos

plugins:
  - "@kingdarboja/serverless-plugin-typescript"

frameworkVersion: "2"

useDotenv: true

provider:
  name: aws
  runtime: nodejs12.x
  stage: dev
  region: eu-west-1
  environment:
    DYNAMODB_TABLE: ${self:service}-${opt:stage, self:provider.stage}
    COGNITO_USER_POOL_ID:
      Ref: CognitoUserPool
    COGNITO_CLIENT_ID:
      Ref: CognitoUserPoolClient
  iamRoleStatements:
    - Effect: Allow
      Action:
        - dynamodb:Query
        - dynamodb:Scan
        - dynamodb:GetItem
        - dynamodb:PutItem
        - dynamodb:UpdateItem
        - dynamodb:DeleteItem
      Resource: "arn:aws:dynamodb:${opt:region, self:provider.region}:*:table/${self:provider.environment.DYNAMODB_TABLE}"

functions:
  todos-proxy:
    handler: handler.todos
    events:
      - http:
          path: /todos/signin
          method: post
          cors: true
      - http:
          path: /todos/signup
          method: post
          cors: true
      - http:
          path: /todos/{proxy+}
          method: any
          cors: true
          authorizer:
            type: COGNITO_USER_POOLS
            authorizerId:
              Ref: ApiGatewayAuthorizer
    environment:

resources:
  - ${file(aws/cognito.yml)}
  - ${file(aws/dynamodb.yml)}
